# ============================================================================
# SSM Automation Document for Jira Integration
# ============================================================================
#
# This document allows Jira Automation to trigger code generation via SSM.
# Jira Automation has native AWS integration that can invoke SSM Documents,
# which then invoke our generate-code Lambda directly (bypassing API Gateway).
#
# Flow:
#   Jira Issue → Jira Automation Rule → AWS (assume role) → SSM Document → Lambda
#
# Setup Steps:
#   1. Deploy with enable_jira_integration = true (uses placeholder external ID)
#   2. Copy the atlassian_automation_role_arn output
#   3. In Jira Automation, create a new AWS connector using the Role ARN
#   4. Atlassian generates an External ID - copy it
#   5. Update jira_external_id in your tfvars with the real External ID
#   6. Re-deploy Terraform to update the trust policy
#   7. Create Jira Automation rule that invokes the SSM document
#
# Jira Smart Values Mapping (defaults pre-populated for easy setup):
#   - issueKey        → {{issue.key}}
#   - issueSummary    → {{issue.summary}}
#   - issueDescription → {{issue.description}}
#   - componentKey    → {{issue.components.name}}
#   - label           → {{issue.labels}}
#
# The componentKey should match the GitHub repo path (e.g., "bcarpio/my-repo").
#
# Supported Labels:
#   - approved-for-generation: Full code generation (plan + code + tests + PR)
#   - approved-for-plan: Plan-only mode (generates plan and PR, no code generation)
# Teams create a Jira component with this name to enable the integration.
# ============================================================================

# Atlassian Automation AWS account ID (global static value - same for all customers)
locals {
  atlassian_automation_account_id = "815843069303"
}

# ============================================================================
# SSM Automation Document
# ============================================================================

resource "aws_ssm_document" "jira_automation" {
  count = var.enable_jira_integration ? 1 : 0

  name            = "${var.environment}-${var.app_name}-jira-automation"
  document_type   = "Automation"
  document_format = "YAML"

  content = <<DOC
schemaVersion: '0.3'
description: 'Generate code from Jira user stories via OutcomeOps AI'
parameters:
  issueKey:
    type: String
    description: 'Jira issue key (e.g., PROJ-123)'
    default: '{{issue.key}}'
  issueSummary:
    type: String
    description: 'Jira issue summary/title'
    default: '{{issue.summary}}'
  issueDescription:
    type: String
    description: 'Jira issue description/user story'
    default: '{{issue.description}}'
  componentKey:
    type: String
    description: 'Jira component name - should match GitHub repo path (e.g., owner/repo)'
    default: '{{issue.components.name}}'
  label:
    type: String
    description: 'Label that triggered the automation (approved-for-generation or approved-for-plan)'
    default: '{{issue.labels}}'
mainSteps:
  - name: buildPayload
    action: 'aws:executeScript'
    inputs:
      Runtime: python3.11
      Handler: script_handler
      Script: |
        import json
        def script_handler(events, context):
          payload = {
            'source': 'jira',
            'issueKey': events['issueKey'],
            'issueSummary': events['issueSummary'],
            'issueDescription': events['issueDescription'],
            'componentKey': events['componentKey'],
            'label': events['label']
          }
          return {'payload': json.dumps(payload)}
      InputPayload:
        issueKey: '{{ issueKey }}'
        issueSummary: '{{ issueSummary }}'
        issueDescription: '{{ issueDescription }}'
        componentKey: '{{ componentKey }}'
        label: '{{ label }}'
    outputs:
      - Name: payload
        Selector: $.Payload.payload
        Type: String
    description: 'Build properly escaped JSON payload'
  - name: invokeCodeGenerationLambda
    action: 'aws:invokeLambdaFunction'
    inputs:
      FunctionName: '${var.environment}-${var.app_name}-generate-code'
      Payload: '{{ buildPayload.payload }}'
    description: 'Invoke Lambda to generate code from Jira user story'
DOC

  # Share document with Atlassian Automation AWS account
  permissions = {
    type        = "Share"
    account_ids = local.atlassian_automation_account_id
  }

  tags = {
    Purpose = "jira-automation"
  }
}

# ============================================================================
# IAM Role for Atlassian Automation (cross-account trust)
# ============================================================================
# This role is assumed by Atlassian's AWS account when Jira Automation triggers.
# The External ID is generated by Atlassian when you configure the AWS connector.
#
# Uses terraform-aws-modules/iam for standardized role creation.

module "atlassian_automation_role" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-assumable-role"
  version = "~> 5.0"

  count = var.enable_jira_integration ? 1 : 0

  create_role = true

  # Role name must start with "atlassian-automation-" for Jira to recognize it
  # Include account number to allow multi-account deployments
  role_name = "atlassian-automation-${data.aws_caller_identity.current.account_id}-${var.environment}-${var.app_name}"

  # Trust Atlassian's AWS account
  trusted_role_arns = ["arn:aws:iam::${local.atlassian_automation_account_id}:root"]

  # External ID from Jira Automation AWS connector (no MFA required)
  role_requires_mfa   = false
  role_sts_externalid = [var.jira_external_id]

  # Inline policies for SSM and Lambda access
  inline_policy_statements = [
    # SSM Document discovery and execution
    {
      sid    = "SSMAutomationAccess"
      effect = "Allow"
      actions = [
        "ssm:ListDocuments",
        "ssm:DescribeDocument",
        "ssm:GetDocument",
        "ssm:GetParameters",
        "ssm:StartAutomationExecution",
        "ssm:GetAutomationExecution",
        "ssm:DescribeAutomationExecutions",
        "ssm:StopAutomationExecution"
      ]
      resources = ["*"]
    },
    # Lambda invocation for generate-code
    {
      sid    = "LambdaInvocation"
      effect = "Allow"
      actions = [
        "lambda:InvokeFunction"
      ]
      resources = [
        module.generate_code_lambda.lambda_function_arn
      ]
    }
  ]

  tags = {
    Purpose = "atlassian-automation"
  }
}

# ============================================================================
# Outputs
# ============================================================================

output "jira_automation_document_name" {
  description = "Name of the SSM Automation Document for Jira integration"
  value       = var.enable_jira_integration ? aws_ssm_document.jira_automation[0].name : null
}

output "jira_automation_document_arn" {
  description = "ARN of the SSM Automation Document for Jira integration"
  value       = var.enable_jira_integration ? aws_ssm_document.jira_automation[0].arn : null
}

output "jira_automation_role_arn" {
  description = "ARN of the IAM role for Atlassian Automation - use this when configuring the AWS connector in Jira"
  value       = var.enable_jira_integration ? module.atlassian_automation_role[0].iam_role_arn : null
}
