variable "environment" {
  type        = string
  description = "Environment name (dev or prd)"
  validation {
    condition     = contains(["dev", "prd"], var.environment)
    error_message = "Environment must be 'dev' or 'prd'."
  }
}

variable "app_name" {
  type        = string
  description = "Application name"
  default     = "outcome-ops-ai-assist"
}

variable "aws_region" {
  type        = string
  description = "AWS region"
}

variable "repos_to_ingest" {
  type = list(object({
    name    = string
    project = string
    type    = string # "application" or "standards"
  }))
  description = "List of repositories to ingest into the knowledge base"
  default = [
    {
      name    = "outcome-ops-ai-assist"
      project = "bcarpio/outcome-ops-ai-assist"
      type    = "standards"
    }
  ]
}

variable "github_usernames_to_tag" {
  type        = string
  description = "Comma-separated GitHub usernames to tag when tests fail (e.g., 'user1,user2' for teams or 'user1' for single user)"
  default     = ""
  validation {
    condition     = can(regex("^[a-zA-Z0-9_,-]*$", var.github_usernames_to_tag))
    error_message = "GitHub usernames must contain only alphanumeric characters, underscores, hyphens, and commas."
  }
}

# ============================================================================
# Integration Toggles
# ============================================================================

variable "enable_github_issue_integration" {
  type        = bool
  description = "Enable GitHub Issues integration - webhook triggers code generation from issue labels"
  default     = true
}

variable "enable_jira_integration" {
  type        = bool
  description = "Enable Jira Automation integration via SSM Document"
  default     = false
}

variable "jira_external_id" {
  type        = string
  description = "External ID from Jira Automation AWS connector setup (required if enable_jira_integration is true). Generated by Atlassian when configuring the AWS integration."
  default     = ""
}

# ============================================================================
# OutcomeOps License Configuration
# ============================================================================

variable "outcomeops_license_layer_arn" {
  type        = string
  description = "ARN of the OutcomeOps license validator Lambda layer"
  default     = ""
}

variable "outcomeops_license_ssm_param" {
  type        = string
  description = "SSM parameter path for the OutcomeOps license key"
  default     = "/outcomeops/license/key"
}

variable "outcomeops_license_server_url" {
  type        = string
  description = "URL of the OutcomeOps license server for usage reporting"
  default     = "https://license.outcomeops.ai"
}

# ============================================================================
# Performance Tuning
# ============================================================================

variable "enable_bedrock_cooldown" {
  type        = bool
  description = "Enable cooldown between Bedrock API calls to prevent throttling. Disable for enterprise accounts with high quotas."
  default     = true
}

# ============================================================================
# Resource Tags
# ============================================================================

variable "tags" {
  type        = map(string)
  description = "Additional tags to apply to all resources (merged with default tags)"
  default     = {}
}

# ============================================================================
# Chat UI Deployment (Fargate + Internal ALB)
# ============================================================================

variable "deploy_ui" {
  description = "Whether to deploy the chat UI (Fargate + ALB)"
  type        = bool
  default     = false
}

variable "ui_vpc_id" {
  description = "VPC ID for UI deployment"
  type        = string
  default     = ""
}

variable "ui_private_subnet_ids" {
  description = "Private subnet IDs for Fargate tasks and internal ALB"
  type        = list(string)
  default     = []
}

variable "ui_container_image" {
  description = "Container image for UI (nginx + React build)"
  type        = string
  default     = ""
}

variable "ui_alb_internal" {
  description = "Make the ALB internal (VPC-only access). Set to false for public ALB secured by OIDC."
  type        = bool
  default     = true
}

# ============================================================================
# OIDC Authentication (Azure AD)
# ============================================================================

variable "domain" {
  description = "Domain name for the application (e.g., 'outcomeops.ai'). Requires a Route53 hosted zone for this domain."
  type        = string
  default     = ""
}

variable "ui_subdomain" {
  description = "Subdomain for the chat UI (e.g., 'outcomeops' creates outcomeops.domain.com for prd, outcomeops-dev.domain.com for dev)"
  type        = string
  default     = "outcomeops"
}

variable "oidc_enabled" {
  description = "Enable OIDC authentication via Azure AD on the ALB"
  type        = bool
  default     = false
}

variable "oidc_client_id" {
  description = "Azure AD Application (client) ID for OIDC authentication"
  type        = string
  default     = ""
}

variable "oidc_tenant_id" {
  description = "Azure AD Directory (tenant) ID for OIDC authentication"
  type        = string
  default     = ""
}
